version: '3.4'

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER="postgres"
      - POSTGRES_PASSWORD="postgres"
      - POSTGRES_DB="myApp_dev"
    ports:
      - 54320:5432
    volumes:
      - dbdata:/var/lib/postgresql/data

  # redis:
  #   image: redis:latest
  #   ports:
  #     - "6379:6379"

  # web:
  #   build: .
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - db
  #     - redis
  #   environment:
  #     - DATABASE_URL=postgres://postgres:password@db:5432/postgres
  #     - REDIS_URL=redis://redis:6379
  #   volumes:
  #     - .:/app

volumes:
  dbdata: