version: '3.9'

services:
  web:
    build: .
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    depends_on:
      - db
    environment:
      - RAILS_ENV=development
      - INSIDE_DOCKER=true
    command: bash -c "rm -f tmp/pids/server.pid && bin/rails server -b 0.0.0.0"

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: myapp_development

volumes:
  postgres_data:
