
# docker-compose.yml
version: '3.9'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/myapp
    stdin_open: true        # ✅ enables interactive input
    tty: true               # ✅ enables terminal-like behavior
    depends_on:
      - db
    environment:
      - RAILS_ENV=development
      - INSIDE_DOCKER=true
    command: bash -c "rm -f tmp/pids/server.pid && bin/rails server -b 0.0.0.0"

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: myapp_development

volumes:
  postgres_data:





# version: '3.4'

# services:
#   db:
#     image: postgres:latest
#     environment:
#       - POSTGRES_USER="postgres"
#       - POSTGRES_PASSWORD="postgres"
#       - POSTGRES_DB="myApp_dev"
#     ports:
#       - 54320:5432
#     volumes:
#       - dbdata:/var/lib/postgresql/data

#   # redis:
#   #   image: redis:latest
#   #   ports:
#   #     - "6379:6379"

#   # web:
#   #   build: .
#   #   ports:
#   #     - "3000:3000"
#   #   depends_on:
#   #     - db
#   #     - redis
#   #   environment:
#   #     - DATABASE_URL=postgres://postgres:password@db:5432/postgres
#   #     - REDIS_URL=redis://redis:6379
#   #   volumes:
#   #     - .:/app

# volumes:
#   dbdata: