
# docker-compose.yml
version: '3.8'

services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle install && rails server -b 0.0.0.0 -p 3000"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_HOST: db
    stdin_open: true
    tty: true

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:




# version: '3.4'

# services:
#   db:
#     image: postgres:latest
#     environment:
#       - POSTGRES_USER="postgres"
#       - POSTGRES_PASSWORD="postgres"
#       - POSTGRES_DB="myApp_dev"
#     ports:
#       - 54320:5432
#     volumes:
#       - dbdata:/var/lib/postgresql/data

#   # redis:
#   #   image: redis:latest
#   #   ports:
#   #     - "6379:6379"

#   # web:
#   #   build: .
#   #   ports:
#   #     - "3000:3000"
#   #   depends_on:
#   #     - db
#   #     - redis
#   #   environment:
#   #     - DATABASE_URL=postgres://postgres:password@db:5432/postgres
#   #     - REDIS_URL=redis://redis:6379
#   #   volumes:
#   #     - .:/app

# volumes:
#   dbdata: